plugins {
    id 'fabric-loom' version '1.17.11'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
}

dependencies {
    // Minecraft 26.2
    minecraft "com.mojang:minecraft:${minecraft_version}"

    // Fabric Loader
    implementation "net.fabricmc:fabric-loader:${loader_version}"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand(
            "version": project.version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25

    withSourcesJar()
}
